### ISSUE TITLE
Can't select Dates

### ISSUE THREAD

**Issue by wildeir** [aronwoost/google-calendar-hours#115]
I can no longer select certain dates in the custom field. So basically I can't really use this app

**Comment by aronwoost** [comment]
Hi! I just tested and it works for me. What browser are you using?

**Comment by wildeir** [comment]
I am using Chrome.

**Comment by wildeir** [comment]
I noticed whats up. I when to select 04/03/2021 thru 04/09/2021 but with both slots, it selected the date before.

**Comment by aronwoost** [comment]
> it selected the date before

Can you elaborate on this? What exactly do you mean? Can you maybe provide a video?

**Comment by wildeir** [comment]
Here's the screen recording.
https://user-images.githubusercontent.com/82234686/114431049-eaeee080-9b73-11eb-85a1-58e0bf3b4050.mov

**Comment by aronwoost** [comment]
🤯🤯🤯

Do you experience the same behavior when you use the date input here? https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

Also, would you be so kind and test on Firefox?

**Comment by wildeir** [comment]
Under that link you sent, no, I don't experience the same behavior. Checking Firefox right now.

**Comment by wildeir** [comment]
Just checked firefox, the same issue is coming up.

**Comment by aronwoost** [comment]
Thank you so much for reporting this issue! 💐

I was able to reproduce it by setting my timezone to west coast.

I just deployed a fix. Selecting the dates should work now. Can you pls double check if the calculations are also correct? 👍

**Comment by wildeir** [comment]
Works now. Thank you so much for this app!!!!!

**Comment by aronwoost** [comment]
💪
