### ISSUE TITLE
Overly precise hour counts (to over a dozen decimal places)

### ISSUE THREAD

**Issue by TiE23** [aronwoost/google-calendar-hours#139]
I have some calendar events that have durations that don't end in clean, obvious numbers. Such as an exactly 13-minute-long event. I believe I have more than a few of them. Adding them all together seems to lead to some display issues.

Whatever the cause, there are some farcically precise floating-point values on display in the summary.

![image](https://user-images.githubusercontent.com/2433505/117176422-ddf19580-ad9d-11eb-8e02-d9ea8b7ec933.png)

Rounding these down to two decimal places would work well.

**Comment by aronwoost** [comment]
Thanks for reporting this issue!

Can you help be debugging this issue? I'm unable to reproduce it by setting a 13min event. It probably has - like you stated - something to do with the events being add up.

**Comment by aronwoost** [comment]
Thanks so much for providing the test calendar! ❤️

I just deployed a fix. Pls check if it's working for you (for me it does!).

**Comment by TiE23** [comment]
And... that fixed it! Very cool! Thanks
