### ISSUE TITLE
only the first 83 of the total 90 events are shown

### ISSUE THREAD

**Issue by paulsclevenger** [aronwoost/google-calendar-hours#142]
All 90 events are on the same calendar and I can't figure out why the last 7 events are not included in the total count.

![Screen Shot 2021-05-26 at 9 26 18](https://user-images.githubusercontent.com/84819877/119584955-aad27d00-be04-11eb-9729-b16ab7e835bc.png)

![Screen Shot 2021-05-26 at 9 25 49](https://user-images.githubusercontent.com/84819877/119584939-a312d880-be04-11eb-94a6-d5edbd554758.png)

**Comment by aronwoost** [comment]
Thanks for reporting this issue!

Can you share me the calendar (maybe clone before)? So I can test. 🥷

**Comment by paulsclevenger** [comment]
Hi Aron,

Here is the link:
https://calendar.google.com/calendar/u/0?cid=Y185OXUybHZmc2dtbG11bmprZWJuczB0ZDMxMEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t

Paul

**Comment by aronwoost** [comment]
For me the calendar doesn't contain any events. Can you double check? At what dates are the events suppose to be?

**Comment by aronwoost** [comment]
Looking at your screenshot again I can imagine what the issue might be.

The app only takes into account future events from today plus 1 year. Reason is that otherwise recurring events would be fetched from Google until 2300 or something. So we have to set a limit somewhere.

Does this makes sense to you?

**Comment by aronwoost** [comment]
Maybe I could extend it to "today plus 2 years". That would fix your issue, right?

**Comment by beetlelea** [comment]
I would love the today plus 2 years option. I'm also experiencing the same problem. I have to submit a full 2022 calendar to our board by Sept of this year. The current settings won't let me grab anything beyond a year from today. 

Thanks so much and you all are awesome!

**Comment by aronwoost** [comment]
Sure! I'm actually surprise how far in the future people are using this tool. 😊😅💪💪💪

I just deployed a fix. Pls confirm that it's working for you.

**Comment by beetlelea** [comment]
It works. Thanks so much!
