### ISSUE TITLE
Unable to sum duration all calendars combined

### ISSUE THREAD

**Issue by alexander-47u** [aronwoost/google-calendar-hours#143]
Hi there,

Thank you for creating such a useful tool. Is there a possibility to sum all calendars, instead of calculating the time of each?
I also want to calculate the time of 1 or 2 months ago, is this possible?

**Comment by alexander-47u** [comment]
A log out button would also be nice :D

**Comment by beetlelea** [comment]
Does this work? When I do it this way, it gives a full count of the month. I can click on details and get more from there.
![image](https://user-images.githubusercontent.com/87545598/125998870-6d03040f-bf7f-4443-87e4-8847cf64a7e4.png)

**Comment by aronwoost** [comment]
I'm not gonna implement the feature to sum up all available calendars. This is out of scope of this app. 👍
