### ISSUE TITLE
Issue : Calculating hours for events marked as free !?

### ISSUE THREAD

**Issue by ghost** [aronwoost/google-calendar-hours#157]
It should Ignore Events that are Marked as FREE

**Comment by aronwoost** [comment]
What is `FREE`? Can you share a calendar?

**Comment by baljeetsingh-tekdi** [comment]
![image](https://user-images.githubusercontent.com/89573485/131437504-217ebfe8-3096-4641-a780-eb9d31356af0.png)

Event / Time slot that exist on Calendar and is marked as FREE slot.
It would be great to have them ignored - may be a check box says Encluded  / Exclude Free event in calculation

**Comment by aronwoost** [comment]
Thanks! I wasn't aware of this type. I'll have a look. 💪

**Comment by baljeetsingh-tekdi** [comment]
Glad to see your response as well as focus on your product -  solution.

thanks for all you do.

**Comment by baljeetsingh** [comment]
GHOST - moved to a (this) account :-)

**Comment by aronwoost** [comment]
Following up on this. Apparently there is no way to read this variable via the [Google Calendar API](https://developers.google.com/calendar/api/v3/reference/events#resource). 😕 So I'm afraid I need to close this ticket.
