### ISSUE TITLE
Idea: Fetch events more frequently

### ISSUE THREAD

**Issue by fross123** [aronwoost/google-calendar-hours#160]
Thoughts on fetching events more frequently? I find that a page reload after an update to my google calendar is pretty inconvenient, so I was thinking it might be nice to fetch events when you click "next" or "previous". Or even just a "refresh events" button somewhere.

I'm happy to work on this, but are there any thoughts before I spend time on it? Any reason it was not designed that way to begin with, etc...?

**Comment by aronwoost** [comment]
Hi @fross123, thanks for your suggestion and sorry for the late response. 😊

This is a valid feature request. However, every feature needs maintenance. And this is typically something that becomes problematic in open source projects. Thats why I think it's better to just stick to `cmd + R` which is free. And I like free features. 😅
