### ISSUE TITLE
Feature request: count number of events / select multiple calendars 

### ISSUE THREAD

**Issue by nurps** [aronwoost/google-calendar-hours#173]
Hours is great, but having a counter of how many events are in would be great too.

And maybe selecting multiple calendars at once.

**Comment by aronwoost** [comment]
Thanks for your suggestion! 💪

Displaying total number of events it a good idea! I just release a new version where the total number of events is displayed in the "show more" button. Please check if this works for you. 😊

Selecting multiple calendars can't be easily implemented as this would raise significant UX challenges and Google does not provide an easy way to fetch the events of multiple calendars.

**Comment by nurps** [comment]
Thanks, this is a lot easier than using the search in google calendar, copying in to a text editor and have it count lines. :)

Also defining a custom time frame makes it a great tool.
