### ISSUE TITLE
Feature request:   Need select all calendars once 

### ISSUE THREAD

**Issue by turkdeniz** [aronwoost/google-calendar-hours#174]
Hi, 

Firstly thank yo for this app it is  very beneficial for calendar user. 
So,  I want to select my all calendars once and take report for  all of them.
Thank you so much.

**Comment by aronwoost** [comment]
Thanks for your suggestion! 💪

Displaying all hours from all calendars is not (easily) possible as Google does not provide an easy way to fetch the events of multiple calendars. 🤷‍♀️

You will need to find a way to work around it.

**Comment by turkdeniz** [comment]
Hi again, 

Thank you so much your replay :) so it is mean also not possible to report that how many free hours available on calendar or calendars .
