### ISSUE TITLE
Rebuild views with react.js

### ISSUE THREAD

**Issue by aronwoost** [aronwoost/google-calendar-hours#26]

**Comment by gustawdaniel** [comment]
What do you think about vue.js? If you know `vue` I can refactor code replacing backbone by `vue`. I looking for tool like this for my own usage, so I will present my vision of key features:

- generating raports inspired by toggle (with visual representation of tasks)
- detecting tags by \#
- detecting keywords by UPPERCASE
- detecting subcategories by syntax CATEGORY.SUBCATEGORY or CATEGORY->SUBCATEGORY

Technologies:

- vue dashboard (free) -> https://demos.creative-tim.com/vuetify-material-dashboard
- amcharts (free) -> https://www.amcharts.com/demos/ 

This is huge change of this project and I estimating it on about 20h so before start I would like to discuss with you If it is in agree with your vision of this project. If something is important for you we can consider this before any work was done.

**Comment by aronwoost** [comment]
Thats for your contribution!

I am not firm with vue. Thats why I would not go with it for now. But I'm still hoping to find time to rework the project with react/redux.

**Comment by damjanuzelac** [comment]
Hi guys, I really like this project and find it quite useful. It would be great if it had some more (visual) features. I'm a designer by trade and I was thinking I could help with the UI if you ever get to reworking this.

**Comment by aronwoost** [comment]
@damjanuzelac Thank you for your offer. I find this an awesome idea!

Feature wise IMO this product is kinda complete (for my use case at least). However it could definitely use some UX/UI improvements. So I'm absolutely open for any idea there.

Fair warning: I don't know when I find time to rework this project onto a more modern tech stack. I don't think that I'd apply UI change to the existing structure. I'd rather apply then on a rewrite...

**Comment by aronwoost** [comment]
Close old and stale issues.
