### ISSUE TITLE
Make it "installable" with a manifest.json

### ISSUE THREAD

**Issue by friedger** [aronwoost/google-calendar-hours#29]

**Comment by aronwoost** [comment]
How does this work? You have a link what you have in mind?

**Comment by friedger** [comment]
See for example https://blog.mozilla.org/firefox/progressive-web-apps-whats-big-deal/

https://developers.google.com/web/fundamentals/web-app-manifest/

Or
https://developer.mozilla.org/en-US/docs/Web/Manifest

**Comment by aronwoost** [comment]
Thanks for the suggestion and the links!

After reading the docs I don't think there is enough value to judge implementation time. This app works only online, so there is very little benefit for offline capabilities. Also I don't fully unterstand how (and if) the OAuth flow would work.

Still a super awesome suggestion. 👍🤝

**Comment by friedger** [comment]
@aronwoost The main motivation for this issue was that I can add it to my home screen on Android. There is no need to make it a 100% PWA. The implementation effort for the install feature is minimal, just create a manifest.json file and add an icon and description. I am happy to send a pull request if you would consider merging it.

**Comment by aronwoost** [comment]
Sure, sending a PR would be awesome!
