### ISSUE TITLE
Getting OAuth2 Error

### ISSUE THREAD

**Issue by skhillon** [aronwoost/google-calendar-hours#33]
In Chrome [64.0.3282.167 (Official Build) (64-bit)] I'm going to the page and clicking "Connect to Google Calendar", but I'm getting the following error:

> Error: redirect_uri_mismatch

> The redirect URI in the request, https://google-calendar-hours.com/auth.html, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/502172359025.apps.googleusercontent.com?project=502172359025

Going to the developer console page simply says "Failed to load". Note that this happens in Incognito mode too.

**Comment by aronwoost** [comment]
Works for me. Can you provide steps to reproduce?

**Comment by aronwoost** [comment]
Issue should be fixed. 🤙 Pls confirm.

**Comment by skhillon** [comment]
Fixed, just used it! 👌
