### ISSUE TITLE
Add functionality for Office 365

### ISSUE THREAD

**Issue by 123trickster** [aronwoost/google-calendar-hours#34]
Hey guy! Love this app. Currently I use it by combining Outlook 365 and gmail. Basically Iopen Calendar ICS from Outlook on my GMAIL calendar and then your program can count the hours. 
Problem is Google takes a really long time to refresh this Calendar. So wanted to see if possible to make this into an Outlook Calendar counter.

**Comment by aronwoost** [comment]
Happy about a PR. 😜👍
