### ISSUE TITLE
Can you add screenshots to docs

### ISSUE THREAD

**Issue by gustawdaniel** [aronwoost/google-calendar-hours#38]
I would like to see something like landing page with more info about `how it works` for end user.

On website

> https://google-calendar-hours.com/

Or in README you can add image like this one.

![zrzut ekranu z 2019-01-05 20-10-20](https://user-images.githubusercontent.com/16663028/50728189-4ffe3500-1126-11e9-86d2-707de027fa97.png)

**Comment by aronwoost** [comment]
Would you like to submit a PR for that?
