### ISSUE TITLE
Week range is inaccurate and adds an extra day

### ISSUE THREAD

**Issue by nickmadedesign** [aronwoost/google-calendar-hours#41]
Hi!

The Week feature adds an extra day. For example, 03.06.2019 - 10.06.2019 (June 6 — June 10).

If the week starts on Monday (June 3), it ends on Sunday (June 9).

The downside is it will add extra hours for the following day (June 10).

It appears to simply add 7 to the start date rather than account for the first day and move 6 from there.

**Comment by aronwoost** [comment]
@nickmadedesign Can you pls check if this issue is still valid? I reworked the project with a new stack. It might be that the issue just vanished... :magic:

**Comment by aronwoost** [comment]
Pls re-open if issue is still present. 👍
