### ISSUE TITLE
Unable to choose sign in

### ISSUE THREAD

**Issue by DonnalynnRiley** [aronwoost/google-calendar-hours#48]
When I try to choose a calendar I get a message that "Sign in with Google temporarily disabled for this app"
<img width="640" alt="Screenshot 2019-09-23 10 45 07" src="https://user-images.githubusercontent.com/55703935/65436027-761c5000-ddef-11e9-995f-1d7e61137609.png">

**Comment by aronwoost** [comment]
Yes, I'm in contact with google to verify the app. Sorry. 😕

**Comment by raynamharris** [comment]
I got the same error message today. Glad I'm not the only one, but it makes me sad :(

**Comment by aronwoost** [comment]
Yeah, it's annoying. 😕

The verify process is actually running for quite a while. However, since yesterday google is disabling apps.

But no worries, we will be there hopefully soon... 🙃

**Comment by maximilianomerialdo** [comment]
Let's wait, and tempt again.

**Comment by chocolatethunder** [comment]
Google is going full out because of the recent spam/phishing attack vulnerabilities discovered in Google Calendar.

**Comment by aronwoost** [comment]
We are back! 🎉🎉🎉
