### ISSUE TITLE
The daily calculation seems not accurate if the item span two days or reach 00:00

### ISSUE THREAD

**Issue by zuozuofei** [aronwoost/google-calendar-hours#60]
The daily calculation seems not accurate if the item spans two days or reach 00:00. If I have some items between 23:30-0:00 and 0:00-0:30 it seems doesn't calculate.

**Comment by consideRatio** [comment]
I observed this as well when I was comparing the weekly total and the daily total.

My expected behavior would be to see the calendar entry spanning across 00:00 would be counted up until 00.00 for one date, and for the other date counted from 00.00.

**Comment by aronwoost** [comment]
@consideRatio A fix to this issue has been deployed. 🦄 Pls confirm that it works for you.

**Comment by consideRatio** [comment]
@aronwoost everything works great and as I would expect :) Thank you for your work on this project @aronwoost!!

:unicorn: :rocket: :moon:

**Comment by aronwoost** [comment]
😊
