### ISSUE TITLE
Date formatting not compatible with google sheets

### ISSUE THREAD

**Issue by Squirenetic** [aronwoost/google-calendar-hours#66]
First off, I love this tool! I work as a consultant, and this makes handling logging of hours and preparing monthly invoices a breeze, so thanks!

Just one teeny tiny request: The csv output date format **DD.MM.YYYY HH:mm** doesn't play well with google sheets, so I have to fiddle a bit after import. A change to **YYYY-MM-DD HH:mm** – either as default or as an option – would make things even smoother :)

**Comment by aronwoost** [comment]
Thanks for the feedback!

Yes, I agree we can be more standard here. Would ISO date `2020-10-06T17:38:03.927Z` also work? Because thats the gold standard I think.

**Comment by aronwoost** [comment]
I'm correctly reworking this app to a more modern tech stack. I'll apply the change once reworking is done. Fair warning: this will take some weeks... 😉😅🤷‍♀️
