### ISSUE TITLE
Make a Chrome extension out of this?

### ISSUE THREAD

**Issue by nuc134r** [aronwoost/google-calendar-hours#74]

**Comment by aronwoost** [comment]
How to do this? 🤔

**Comment by nuc134r** [comment]
It seems not very hard to wrap the entire app into a Chrome extension so it can be opened in a popup form anywhere without occupying the whole tab.

Check Google's documentation if you're up to that. My use case of this expired with the end of working from home. :)

**Comment by aronwoost** [comment]
> My use case of this expired with the end of working from home. :)

😊😊😊 Good for you!

I'm unwilling to invest toward that direction. Maybe someone will come up with a PR at some points... 👍
