### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by danrbn** [aronwoost/google-calendar-hours#75]
Thank you so much for your project! As a private contractor, it is essencial on my day to day for calculating bills for clients.
Unfortunately, it has stooped working for me a few months ago. Whenever I try to access my calendar, it shows Error 503 and a link I can't copy / click. 
Is there a solution? Did I do something wrong?

**Comment by aronwoost** [comment]
For me it works as expected. 🤷‍♀️

https://google-calendar-hours.com

Can you provide more details?

**Comment by danrbn** [comment]
![image](https://user-images.githubusercontent.com/76955273/103557039-619f8200-4e91-11eb-9cf1-67b33b6e05e6.png)
This error message appears when I try calculating for my own calendar. I can't click or copy the link that appears. Clicking OK makes the message disappear, but nothing loads. All other calendars I access with my login are working just fine.

**Comment by aronwoost** [comment]
This is interesting. So not all calendars are broken, but only one particular one? Pls define what "my own calendar" means.

What browser are you using?

**Comment by danrbn** [comment]
Thanks again for you interest.

That's right, only my "standard" calendar is broken. Any other personalized
calendars I have are ok. My wife's calendar, that's shared with me, for
instance, works fine. On her login, her standard calendar works fine, but
mine is, once more, broken.

Using chrome on ubuntu and windows.

Em seg, 4 de jan de 2021 14:29, Aron Woost <notifications@github.com>
escreveu:

**Comment by aronwoost** [comment]
Hmm, ok. I just checked my standard calendar and it works as expected. Can you check, if you applied any access restrictions? Or if the calendar is shared with anyone?

There must be something special with this calendar.

**Comment by danrbn** [comment]
It's shared with my wife, and I couldn't find anything different in terms of settings / restrictions from any other calendar that works. But I guess I found a solution for now: I exported all my data into a new calendar. It worked. Thanks!

**Comment by aronwoost** [comment]
👍👍👍
