### ISSUE TITLE
Make percentage converter

### ISSUE THREAD

**Issue by tehcGuy** [aronwoost/google-calendar-hours#81]
Even though the project seemed to be abandoned, I've really enjoyed it. I hope someday you will implement the converter to percentage. Meaning, the time calculated there will be transformed into percents for each calendar section there

**Comment by pkyeck** [comment]
Hi @tehcGuy – it's not abandoned. Aron is doing a big rework (#83) to switch to react and after this is done, we can certainly add new stuff. What exactly do you mean by "percentages"? Something like selecting a month a showing the different tasks in a pie chart?

**Comment by tehcGuy** [comment]
Precisely! However, it would be nice to add percentage piecharts also for a chosen _day, week, month, year_ :)

**Comment by aronwoost** [comment]
This is a very valid feature request! 👍

However, it comes with high implementation costs and a lot of open UX/UI questions.

So I'd rather have this outside of the app. This can either mean to calculate manually or export the numbers and crunch it in Google Sheets or Excel.

Still: thanks for the feature request. 😊
